# Generated by Django 4.0 on 2021-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirguracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core_media')),
            ],
        ),
    ]
